### ISSUE TITLE
@conda-forge-admin, please add user @monaldoj

### ISSUE THREAD

**Issue by monaldoj** [conda-forge/dbt-spark-feedstock#9]

**Comment by monaldoj** [comment]
@conda-forge/core pinging core to merge PR to update maintainer list

**Comment by xhochy** [comment]
@rxm7706 is quite active these days, thus I would rather wait for him instead of doing an early merge here.

Also: Please consider fixing one of the latest PRs instead of requesting direct maintership access. We would like to give rights based on merit, not request.

**Comment by monaldoj** [comment]
@xhochy @rxm7706 fixed the latest PR, Azure pipelines are now passing, merge to update to 1.7.1

**Comment by rxm7706** [comment]
@monaldoj Thank you for your assistance, PR has been merged.
